### PR TITLE
Add routes and marker functionality

### PR DESCRIPTION
**Pull request by dlintott**
I have added a routes shortcode, to enable displaying a route from Strava in the same way activities are displayed.

I have also added an option to display markers at the start and finish points of the route or activity. This defaults to false to preserve backwards compatibility fro users upgrading their plugin

### CODE REVIEW

**Comment by jrfoell** [comment]
@dlintott I know we don't always strictly follow WP coding standards, but I'm trying to convert to it (gradually). I'm going to do some minor formatting on your PR before merging it.

Most of all - THANK YOU!!!

**Comment by dlintott** [comment]
@jrfoell Cheers! Haven't really done much WP plugin coding before, so haven't really looked at the standards before.. so just tried to stick with what was already there.

**Comment by jrfoell** [comment]
@dlintott do you have a WP.org profile name that you use for development or support? I'd love to give you a shout-out and I can also add you to our plugin contributors list :+1:

**Comment by dlintott** [comment]
@jrfoell I didn't have one.... but I do now! Same name as on here.... dlintott 👍

**Pull request merged**
